applications/tickets/urls.py
# -*- coding: utf-8 -*-
"""
Urls for signup.
"""
from django.conf.urls import patterns, url
from .views import TicketCreateView, TicketPayView, TicketReceiptView, TicketStartView


urlpatterns = patterns(
    '',
    url(r'^$', TicketStartView.as_view(), name='ticket-start'),
    url(r'^order/(?P<ticket_type_slug>[-\w]+)/$', TicketCreateView.as_view(), name='ticket-booking'),
    url(r'^(?P<hashid>\w+)/pay/$', TicketPayView.as_view(), name='ticket-payment'),
    url(r'^(?P<hashid>\w+)/receipt/$', TicketReceiptView.as_view(), name='ticket-receipt'),
)

applications/tickets/models.py
# -*- coding: utf-8 -*-
"""
Models and signals for the activity_priority app.
"""
from datetime import datetime
from hashids import Hashids
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from django.db import models
from django.core.urlresolvers import reverse
from applications.conventions.models import Convention
from django_countries.fields import CountryField
from applications.mail.models import MailTrigger


class Person(models.Model):
    name = models.CharField(max_length=100)
# from annoying.functions import get_object_or_None
# from django.contrib.auth.models import User

import logging
logger = logging.getLogger('debug')
BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))
CURRENCY_CHOICES = (('EUR', '€'), ('NOK', 'NOK'), ('USD', 'US $'), ('LTL', 'LTL'),)


class Payment(models.Model):

    """ Transaction of payment for ticket. """

    ticket = models.ForeignKey('Ticket')
    sum_paid = models.IntegerField()
    currency = models.CharField(
        max_length=3
    )
    transaction_id = models.CharField(
        help_text=_('payment provider transaction id'),
        max_length=50,
        editable=False,
        null=True,
    )
    paid_via = models.CharField(
        max_length=50,
        help_text=_('How was the payment made?'),
    )
    payment_time = models.DateTimeField(
        auto_now=True,
        help_text=_('Time the ticket was paid.'),
    )

    class Meta:
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')

    def __str__(self):
        """ unicode. """
        return '{ticket}, {sum}'.format(
            ticket=self.ticket,
            sum=self.sum_paid,
        )


class TicketManager(models.Manager):

    def unpaid(self):
        return self.filter(status=Ticket.ORDERED)

    def sold_out(self):
        """ Check if all tickets are sold out. """
        paying_participants = self.filter(activated=True).count()
        return paying_participants >= self.ticket_type.max

    def delete_unpaid(self, min_age=24):
        from datetime import timedelta
        from django.utils import timezone
        expiration_date = timezone.now() - timedelta(hours=min_age)
        unpaid_tickets = self.filter(activated=False, order_time__lte=expiration_date)
        unpaid_tickets.update(status=Ticket.CANCELLED)


class Ticket(models.Model):

    """ Specific information about participants and their ticket. """

    ORDERED = 1
    PAID = 2
    CANCELLED = 0
    STATUS_CHOICES = (
        (ORDERED, _('ordered'),),
        (PAID, _('paid'),),
        (CANCELLED, _('cancelled'),),
    )

    hasher = Hashids(min_length=8, salt='salte bjørner')

    objects = TicketManager()

    first_name = models.CharField(
        max_length=100,
        null=True,
    )
    last_name = models.CharField(
        max_length=100,
        null=True,
    )
    email = models.EmailField(
        null=True,
    )
    city = models.CharField(
        max_length=500,
    )
    postal_code = models.CharField(
        max_length=500,
    )
    address = models.CharField(
        max_length=500,
    )
    country = CountryField()
    date_of_birth = models.DateField(
        null=True,
    )
    sum_paid = models.PositiveSmallIntegerField(
        default=0,
    )
    status = models.PositiveSmallIntegerField(
        default=ORDERED,
        choices=STATUS_CHOICES,
        help_text=_('Status of payment.'),
    )
    order_time = models.DateTimeField(
        auto_now_add=True,
        help_text='Time the ticket was ordered',
    )
    ticket_type = models.ForeignKey(
        'TicketType',
        related_name='tickets',
    )
    hashid = models.CharField(
        max_length=100,
        db_index=True,
    )
    comments = models.TextField(blank='True')

    def __str__(self):
        return '{name}'.format(
            name=self.get_full_name(),
            # ticket_type=self.ticket_type,
        )

    def pay(self, **kwargs):
        """ Make payment on ticket. """

        sum_paid = kwargs.pop('sum_paid', self.ticket_type.price)
        currency = kwargs.pop('currency', self.ticket_type.currency)

        if self.ticket_type.currency != currency is not None:
            raise ValueError(
                'Expected currency {}, received {}'.format(
                    self.ticket_type.currency,
                    currency,
                ))

        kwargs.update(
            ticket=self,
            sum_paid=sum_paid,
            currency=currency,
        )
        payment = Payment(**kwargs)
        payment.save()
        self.sum_paid += sum_paid
        self.save()

    @property
    def age(self, at_date=None):
        """ Calculte age of participant """
        if not self.date_of_birth:
            return 0
        if at_date is None:
            at_date = datetime.now()
        return (
            at_date.year -
            self.date_of_birth.year -
            int(
                (at_date.month, at_date.day) <
                (self.date_of_birth.month, self.date_of_birth.day)
            )
        )

    @property
    def convention(self):
        return self.ticket_type.ticket_pool.convention

    def get_full_name(self):
        """Return full name of ticket holder."""
        return u'%s %s' % (self.first_name, self.last_name,)

    def get_address_display(self):
        """Return full name of ticket holder."""
        res = '{address}, {postal_code} {city}, {country}'.format(
            address=self.address,
            postal_code=self.postal_code,
            city=self.city,
            country=self.country.name,
        )
        return res

    def get_absolute_url(self):
        """ Payment or receipt view. """
        kwargs = {'hashid': self.hashid, }
        if self.status == self.ORDERED:
            return reverse(viewname='ticket-payment', kwargs=kwargs,)
        elif self.status == self.PAID:
            return reverse(viewname='ticket-receipt', kwargs=kwargs,)
        else:
            # Cancelled?
            return ''

    def save(self, *args, **kwargs):
        """
        Selects ticket type based on ticket holder's nationality.
        And checks if ticket has been paid for.
        """
        if self.status == self.ORDERED and self.ticket_type.price <= self.sum_paid:
            self.status = self.PAID
            MailTrigger.objects.send_mail(recipient=self, trigger=MailTrigger.TICKET_PAID)
        if self.status == self.PAID and self.ticket_type.price > self.sum_paid:
            self.status = self.ORDERED

        super().save(*args, **kwargs)

        if not self.hashid:
            self.ticket_type.check_availability()
            # import ipdb; ipdb.set_trace()
            self.hashid = self.hasher.encrypt(self.pk)
            super().save(*args, **kwargs)
            MailTrigger.objects.send_mail(recipient=self, trigger=MailTrigger.TICKET_ORDERED)


class TicketPool(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    max_tickets = models.PositiveSmallIntegerField()
    convention = models.ForeignKey(Convention)

    class Meta:
        verbose_name = _('ticket pool')
        verbose_name_plural = _('ticket pools')

    def __str__(self):
        return self.name

    def sold_out(self):
        return self.max_tickets <= self.tickets_sold

    @property
    def tickets_sold(self):
        return sum(
            tt.tickets.exclude(status=Ticket.CANCELLED).count()
            for tt in self.ticket_types.all()
        )


class TicketType(models.Model):

    """ Different ticket types for different participants. """

    COMING_SOON = 0
    FOR_SALE = 1
    SOLD_OUT = 2
    SECRET = 3
    STATUS_CHOICES = (
        (COMING_SOON, _('coming soon')),
        (FOR_SALE, _('for sale')),
        (SOLD_OUT, _('sold out')),
        (SECRET, _('secret')),
    )

    name = models.CharField(max_length=20,)
    price = models.PositiveSmallIntegerField(default=0,)
    currency = models.CharField(choices=CURRENCY_CHOICES, max_length=3)
    ticket_pool = models.ForeignKey(
        TicketPool,
        related_name='ticket_types')
    max_tickets = models.PositiveSmallIntegerField(
        blank=True, null=True,
        help_text=_('only needed if the quota on this ticket type is smaller than the assigned ticket pool.'),
    )
    slug = models.SlugField(
        editable=False,
        db_index=True,
    )

    description = models.TextField(
        help_text=_('Short description of the ticket type.'),
        blank=True,
    )
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES,
        default=SECRET,
    )

    def get_price_display(self):
        return '{price} {currency}'.format(price=self.price, currency=self.get_currency_display())

    def max(self):
        return self.max_tickets or self.ticket_pool.max_tickets

    def check_availability(self):
        if self.status == self.FOR_SALE and self.sold_out():
            self.status = self.SOLD_OUT
            self.save()
        return self.status

    def sold_out(self):
        if self.max() <= self.tickets_sold:
            return True
        if self.ticket_pool.sold_out():
            return True
        return False

    @property
    def tickets_sold(self):
        return self.tickets.exclude(status=Ticket.CANCELLED).count()

    def __str__(self):
        """ Return ticket name and price. """
        return '{tickettype} ({price} {currency})'.format(
            # con=self.ticket_pool.convention,
            tickettype=self.name,
            price=self.price,
            currency=self.currency,
        )

    def get_absolute_url(self):
        return reverse(
            viewname='ticket-booking',
            kwargs={'ticket_type_slug': self.slug},
        )

    def save(self, *args, **kwargs):
        self.slug = slugify(r'{ticket_type}-{con}'.format(
            con=self.ticket_pool.convention.name,
            ticket_type=self.name,
        ))[:50]

applications/tickets/templates/_payment-details.html
<table class="details-table small-12 columns">
  {% for payment in ticket.payment_set.all %}
    <tr>
      <th scope="row">Sum paid</th>
      <td>{{ payment.sum_paid }} {{ payment.currency }}</td>
    </tr>
    <tr>
      <th scope="row">Time of payment</th>
      <td>{{ payment.payment_time }}</td>
    </tr>
    <tr>
      <th scope="row">Payment method</th>
      <td>{{ payment.paid_via }}</td>
    </tr>
  {% empty %}
    <tr>
      <th scope="row">Sum paid</th>
      <td>0</td>
    </tr>
  {% endfor %}
</table>

applications/tickets/templates/_payment-info.html
<p>To read about our terms and policies, click on the topics below.</p>
<dl class="trekkspill" data-accordion>
  <dd class="navigation">
    <a href="#payment-information">Payment information</a>
    <div id="payment-information" class="content">
      {% if paymill_live %}
        <p>We accept all major credit cards through our payment provider <a href="https://www.paymill.com/">PayMill</a></p>
        <p>Your credit card information is transmitted securely to PayMill, and will not be stored or accessed by Grenselandet.</p>
        <p>The transaction will be labelled FANTASIFORBUNDET on you credit card statement.</p>
        <p>Your ticket is valid as soon as your payment has been confirmed.</p>
      {% else %}
        {% include '_paymill_not_activated.html' %}
      {% endif %}
    </div>
  </dd>
  <dd class="navigation">
    <a href="#terms-and-conditions">Terms and conditions</a>
    <div id="terms-and-conditions" class="content">
      <p>If for any reason {{ convention }} is cancelled, all purchased tickets will be refunded in full.</p>
      <p>In other cases tickets purchased are non-refundable and non-transferable.</p>
    </div>
  </dd>
  <dd class="navigation">
    <a href="#privacy-policy">Privacy policy</a>
    <div id="privacy-policy" class="content">
      <p>Credit card data submitted when buying a ticket is encrypted and sent directly to our payment provider through a secure connection.</p>
      <p>The personal information submitted to us will not be hared with third parties, but can be used for the promotion of future Grenselandet events and other events organized by Fantasiforbundet.</p>
    </div>
  </dd>
</dl>

applications/tickets/templates/_paymill-form.html
{% load staticfiles %}
{% load sekizai_tags %}

{% addtoblock 'extrajs' %}
<script type="text/javascript">
  var PAYMILL_PUBLIC_KEY = '{{ PAYMILL_PUBLIC_KEY }}';
  var PAYMILL_TEST_MODE= '{{ PAYMILL_TEST_MODE }}';
</script>
<script src="https://bridge.paymill.com/"></script>
<script src="{% static 'js/paymill.js' %}"></script>
<script src="{% static 'js/cc-branddetection.js' %}"></script>
{% endaddtoblock %}

{% addtoblock 'css' %}
  <link rel='stylesheet' type='text/css' href='{% static 'css/paymill.css' %}'>
{% endaddtoblock %}
<form id="payment-form" method="post">

  <div class="row collapse">
    <div class="small-4 columns"><span class="prefix">
      Card number
    </span></div>
    <div class="small-8 columns">
      <input
      class="card-number"
      required="true"
      title=""
      placeholder="0000 0000 0000 0000"
      type="text"
      size="20"
      />
    </div>
  </div>

  <div class="row collapse">
    <div class="small-4 columns"><span class="prefix">
      CVC
    </span></div>
    <div class="small-8 columns">
      <input
      class="card-cvc"
      required="true"
      title="MasterCard, Visa, Diners Club, Discover, and JCB credit and debit cards have a three-digit card security code.
      The code is the final group of numbers printed on the back signature panel of the card.
      American Express cards have a four-digit code printed on the front side of the card above the number."
      placeholder="Card verification code"
      type="text"
      size="4"
      />
    </div>
  </div>

  <div class="row collapse">
    <div class="small-4 columns"><span class="prefix">
      Expiration
    </span></div>
    <div class="small-8 columns">
      <input
         class="card-expiry"
         type="text"
         size="2"
         pattern="^\d\d/\d\d\d\d$"
         placeholder="MM/YYYY"
         required="true"
         title="Expiration date Month/Year"
         type="text"
         />
    </div>
  </div>

  <input class="card-amount" type="hidden" value="{{ ticket.ticket_type.price }}" />
  <input class="card-currency" type="hidden" value="{{ ticket.ticket_type.currency }}" />
  <input name="ticket_hashid" type="hidden" value="{{ ticket.hashid }}" />
  {% csrf_token %}
  {# <button id="payment-button" class="small-12 columns submit-button" type="submit">Submit</button> #}
  <input type="submit" value="Confirm purchase" class="submit-button button expand radius">

</form>

applications/tickets/templates/_paymill_not_activated.html
<p>Unfortunately, our online payment solution is not quite ready yet.</p>
<p>If you have a Norwegian bank account, you can pay by bank transfer. Other particpants can book their tickets now, and we'll contact you with further payment instructions.</p>

applications/tickets/templates/_ticket-form.html
{% load widget_tweaks %}
{% for field in form %}
<div class="row collapse">
  <div class="small-4 columns">
    <span class="prefix">{{ field.label }}</span>
  </div>
  <div class="small-8 columns">
    {% if field.errors %}
      {{ field | attr:"class:error" }}
    {% else %}
      {{ field }}
    {% endif %}
  </div>
  {% for error in  field.errors %}
    <small class="error">{{ error }}</small>
  {% endfor %}
</div>
{% endfor %}

applications/tickets/templates/_ticket-panel.html
{% with ticket_type.ticket_pool.convention as convention %}
<div class="panel radius ticket-panel">
  <div class="row">
    <div class="small-8 columns">
      <h4 class="ticket-name">{{ ticket_type.name }}</h4>
      <div class="ticket-description">
        <table class="details-table">
          {% if ticket %}
          <tr>
            <th scope="row">Ticket Holder</th>
            <td>{{ ticket.get_full_name }}
            </br>{{ ticket.email }}</td>
          </tr>
          {% endif %}
          <tr>
            <th scope="row">Event</th>
            <td>{{ convention }}</td>
          </tr>
          <tr>
            <th scope="row">Location</th>
            <td>{{ convention.location }}</td>
          </tr>
          <tr>
            <th scope="row">Time</th>
            <td>{{ convention.start_time|date }} to {{ convention.end_time|date }}</td>
          </tr>
        </table>
      </div>
    </div>
    <div class="small-4 columns">
      <h4>Full price</h4>
      <p><strong>{{ ticket_type.get_price_display }}</strong></p>
    </div>
  </div>
</div>
{% endwith %}

applications/tickets/templates/base-ticket.html
{% extends "base-template.html" %}

{% block title %}{{ ticket.convention }} ticket for {{ ticket.get_full_name}} {{ convention }}{% endblock %}

{% block content %}
<div class="small-12 columns">
  {% block info %}
  <h1>Title</h1>
  <p>Text.</p>
  {% endblock info %}
  <hr>
</div>

<div class="medium-6 columns">
  {% block ticket-info %}
    <h3><i class="fi-shopping-cart icon"></i> Purchase summary</h3>
    {% include '_ticket-panel.html' %}
    {% include '_payment-info.html' %}
  {% endblock ticket-info %}
</div>
<div class="medium-6 columns">
  {% block form %}
    No form.
  {% endblock form %}
</div>
{% endblock content%}

applications/tickets/templates/festival-over.html
{% extends "base-template.html" %}
{% block title %}Welcome back next time!{% endblock title %}
{% block content %}
  <div class="small-12 columns">
    <h1>{{ convention }} is over for this time</h1>
  </div>
  <div class="medium-12 columns">
    {{ convention.description|linebreaks }}
    <hr>
    <p>
      There's no tickets available at this time.
    </p>
  </div>

{% endblock %}

applications/tickets/templates/paymill-test.html
<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8" />
        <style>
            * {
                font-family:'lucida grande', tahoma, verdana, arial, sans-serif;
                font-size: 14px;
            }
            h2 {
                font-size:16px;
                margin-left: 20px;
            }
            .box {
                border:1px #eee solid;
                background: #fafafa;
                padding: 10px;
                margin: 20px;
            }
            strong {
                margin-top:5px;
                margin-bottom:15px;
                display: block;
            }
            button {
                margin-top:15px;
                display: inline-block; *display: inline; *zoom: 1; padding: 4px 10px 4px; margin-bottom: 0; font-size: 13px; line-height: 20px; *line-height: 20px; color: #333333; text-align: center; text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75); vertical-align: middle; cursor: pointer; background-color: #f5f5f5; background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6); background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6)); background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6); background-image: -o-linear-gradient(top, #ffffff, #e6e6e6); background-image: linear-gradient(top, #ffffff, #e6e6e6); background-repeat: repeat-x; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#e6e6e6', GradientType=0); border-color: #e6e6e6 #e6e6e6 #bfbfbf; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25); *background-color: #e6e6e6; filter: progid:DXImageTransform.Microsoft.gradient(enabled = false); border: 1px solid #cccccc; *border: 0; border-bottom-color: #b3b3b3; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; *margin-left: .3em; -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05); -moz-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05); box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);

            }
            .submit-button {
                margin-left:305px;
            }
            label {
                position: absolute;
                text-align: right;
                width: 150px;
                line-height: 2.0;
            }
            input {
                margin-left: 160px;
            }
        </style>
        <script type="text/javascript" src="https://bridge.paymill.com/"></script>
        <script type="text/javascript" src="https://static.paymill.com/assets/js/jquery/jquery-1.7.2.min.js"></script>
        <script type="text/javascript">

        var PAYMILL_PUBLIC_KEY = '{{ PAYMILL_PUBLIC_KEY }}';
        var PAYMILL_TEST_MODE = '{{ PAYMILL_TEST_MODE }}';

        $(document).ready(function() {

            $("#apikey-form").submit(function(event) {
                event.preventDefault();
                var key = $(".api-key").val();
                logResponse(key);
                PAYMILL_PUBLIC_KEY = key;
            });

            // Legacy credit card form
            $("#card-form").submit(function(event) {
                event.preventDefault();
                try {
                    paymill.createToken({
                        number:     $('#card-form .card-number').val(),
                        exp_month:  $('#card-form .card-expiry-month').val(),
                        exp_year:   $('#card-form .card-expiry-year').val(),
                        cvc:        $('#card-form .card-cvc').val(),
                        cardholder: $('#card-form .card-holdername').val()
                    }, PaymillResponseHandler);
                } catch(e) {
                    logResponse(e.message);
                }
            });

            // 3d secure credit card form
            $("#card-tds-form").submit(function(event) {
                event.preventDefault();
                try {
                    paymill.createToken({
                        number:     $('#card-tds-form .card-number').val(),
                        exp_month:  $('#card-tds-form .card-expiry-month').val(),
                        exp_year:   $('#card-tds-form .card-expiry-year').val(),
                        cvc:        $('#card-tds-form .card-cvc').val(),
                        cardholder: $('#card-tds-form .card-holdername').val(),
                        amount: $('#card-tds-form .card-amount').val(),
                        currency: $('#card-tds-form .card-currency').val()
                    }, PaymillResponseHandler);
                } catch(e) {
                    logResponse(e.message);
                }
            });

            // direct debit form
            $("#debit-form").submit(function(event) {
                event.preventDefault();
                try {
                    paymill.createToken({
                        number: $('.debit-number').val(),
                        bank:  $('.debit-bank').val(),
                        country:   $('.debit-country').val(),
                        accountholder: $('.debit-holdername').val()
                    }, PaymillResponseHandler);
                } catch(e) {
                    logResponse(e.message);
                }
            });

            $("#debit-form .debit-bank").bind("paste cut keydown",function(e) {
                var that = this;
                setTimeout(function() {
                    paymill.getBankName($(that).val(), function(error, result) {
                        error ? logResponse(error.apierror) : $(".debit-bankname").val(result);
                    });
                }, 200);
            });
        });

        function PaymillResponseHandler(error, result) {
            error ? logResponse(error.apierror) : logResponse(result.token);
        }

        function logResponse(res) {
            // create console.log to avoid errors in old IE browsers
            if (!window.console) console = {log:function(){}};

            console.log(res);
            if(PAYMILL_TEST_MODE)
                $('.debug').text(res).show().fadeOut(3000);
        }

        // TODO add CSS3 spinner graphics, IE graceful degradation
        </script>
    </head>
    <body>
        <div style="width:960px;margin:0 auto;">
            <div style="width:440px;float:left;">
                <h2>Payment form types</h2>
                <div class="box">
                    <strong>Legacy credit card</strong>
                    <form id="card-form" action="#" method="POST">
                        <label>Credit card number</label>
                        <input class="card-number" type="text" size="20" value="4111111111111111" />
                        <br>
                        <label>CVC</label>
                        <input class="card-cvc" type="text" maxlength="4" size="4" value="123" />
                        <br>
                        <label>Card holder</label>
                        <input class="card-holdername" type="text" size="20" value="Max Mustermann" />
                        <br>
                        <label>Expiry (MM/YYYY)</label>
                        <input class="card-expiry-month" type="text" size="2" value="12" maxlength="2" />
                        <input class="card-expiry-year" type="text" size="4" value="2015" maxlength="4" style="margin-left: 0px;" />
                        <br>
                        <button class="submit-button" type="submit">Submit</button>
                    </form>
                </div>
                <div class="box">
                    <strong>3DS credit card</strong>
                    <form id="card-tds-form" action="#" method="POST">
                        <label>Credit card number</label>
                        <input class="card-number" type="text" size="20" value="4012888888881881" />
                        <br>
                        <label>CVC</label>
                        <input class="card-cvc" type="text" maxlength="4" size="4" value="123" />
                        <br>
                        <label>Card holder</label>
                        <input class="card-holdername" type="text" size="20" value="Max Mustermann" />
                        <br>
                        <label>Expiry (MM/YYYY)</label>
                        <input class="card-expiry-month" type="text" size="2" value="12" maxlength="2" />
                        <input class="card-expiry-year" type="text" size="4" value="2015" maxlength="4" style="margin-left: 0px;" />
                        <br>
                        <label>Amount</label>
                        <input class="card-amount" type="text" size="4" value="123.45" />
                        <br>
                        <label>Currency</label>
                        <input class="card-currency" type="text" size="4" value="EUR" />
                        <br>
                        <button class="submit-button" type="submit">Submit</button>
                    </form>
                </div>
                <div class="box">
                    <strong>Direct debit</strong>
                    <form id="debit-form" action="#" method="POST">
                        <label>Account number</label>
                        <input class="debit-number" maxlength="10" type="text" size="20" value="12345678" />
                        <br>
                        <label>Bank code number</label>
                        <input class="debit-bank" maxlength="8" type="text" size="20" value="1001001" />
                        <br>
                         <!--[if gte IE 8]><!-->
                        <label>Bank name</label>
                        <input class="debit-bankname" type="text" size="20" disabled="disabled" style="background-color:#eee;" />
                        <br>
                        <!--<![endif]-->
                        <label>Account holder</label>
                        <input class="debit-holdername" type="text" size="20" value="Max Mustermann" />
                        <br>
                        <label>Country</label>
                        <input class="debit-country" type="text" size="20" value="Deutschland" />
                        <br>
                        <button class="submit-button" type="submit">Submit</button>
                    </form>
                </div>
            </div>
            <div style="float:left;width:440px;height:300px;">
                <h2>Debug panel</h2>
                <div class="box" style="height:50px;">
                    <p class="debug"></p>
                </div>

                <h2>Change PAYMILL Public API Key</h2>
                <div class="box">
                    <form id="apikey-form" action="#" method="POST">
                        <input class="api-key" type="text" size="29" value="" style="margin-left: 0px;" />
                        <button class="setkey-button" type="submit" style="margin-top:0;">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

applications/tickets/templates/signup_payment_success.html
{# Return view on successful payment of ticket. #}
{% extends "base-template.html" %}

{% block title %}Book a ticket{% endblock %}
{% block content %}
<h1>Thank you</h1>
<p>Your payment has been registered</p>
<p><a href="{% url 'ticket-pay' %}">View your ticket</a></p>

{% endblock %}

applications/tickets/templates/ticket-create.html
{% extends "base-ticket.html" %}
{% block title %}Book a ticket for {{ convention }}{% endblock %}

{% block info %}
  <h1>Book your ticket</h1>
  <p>Please enter the required information about yourself before proceeding to the checkout page.</p>
{% endblock info %}

{% block form %}
  <h3><i class="fi-torso icon"></i> Ticket holder</h3>
  <form id="registration-form" method="post">
    {% include '_ticket-form.html' %}
    {% csrf_token %}
    <input type="submit" value="Continue" class="radius button expand">
  </form>
{% endblock form %}

applications/tickets/templates/ticket-pay.html
{% extends "base-ticket.html" %}

{% block title %}{{ ticket.convention }} ticket for {{ ticket.get_full_name}} {{ convention }}{% endblock %}

{% block info %}
<h1>Your ticket reservation</h1>
<p>Please enter your credit card information to complete the ticket purchase.</p>
{% endblock info %}

{% block form %}
  {% if paymill_live %}
    <h3><i class="fi-credit-card icon"></i> Credit Card Details</h3>
    {% include '_paymill-form.html' %}
  {% else %}
    <h3><i class="fi-credit-card icon"></i> Payment information</h3>
    <p>Thank you for booking your ticket.</p>
    {% include '_paymill_not_activated.html' %}
  {% endif %}
{% endblock form %}

applications/tickets/templates/ticket-receipt.html
{% extends "base-ticket.html" %}

{% block info %}
  <h1>Your ticket receipt</h1>
  <p>We are looking forward to seeing you at {{ ticket.convention }}!</p>
{% endblock info %}

{% block ticket-info %}
  <h3><i class="fi-torso icon"></i> Ticket information</h3>
  {% include '_ticket-panel.html' %}
{% endblock ticket-info %}

{% block form %}
  <h3><i class="fi-dollar-bill icon"></i> Payment details</h3>
  {% include '_payment-details.html' %}
{% endblock form %}