applications/program/urls.py
# -*- coding: utf-8 -*-
"""
Urls for program.
"""
from django.conf.urls import patterns, url
from .views import schedule, hashid_schedule, sessionlist, reshuffle, public_list, participantlist, blekke, program_oppslag


urlpatterns = patterns(
    '',
    url(r'^$', schedule, name='program-schedule'),
    url(r'^sessions/$', sessionlist, name='program-sessionlist'),
    url(r'^participants/$', participantlist, name='program-participants'),
    url(r'^reshuffle/$', reshuffle, name='program-reshuffle'),
    url(r'^games/$', public_list, name='program-public-list'),
    url(r'^blekke/$', blekke, name='program-blekke'),
    url(r'^oppslag/$', program_oppslag, name='program-oppslag'),
    # url(r'^(?P<hashid>\w+)/p/$', hashid_schedule, name='hashid-schedule'),
)

applications/program/models.py
import statistics
from django.contrib.auth.models import User, Group
from django.db import models
from datetime import timedelta
from applications.conventions.models import Convention
from applications.tickets.models import Ticket

from django.utils.translation import ugettext_lazy as _
from django.utils import formats


def next_convention():
    convention = Convention.objects.next()
    if convention:
        return convention.pk
    else:
        return None


def next_convention_start_time():
    convention = Convention.objects.next()
    if convention:
        return convention.start_time
    else:
        return None


class Participant(User):

    class Meta:
        proxy = True

    def __str__(self):
        return self.get_full_name()

#     def make_organiser(self):
#         organisers = Group.objects.get_or_create(
#             name='{event} organisers'.format(
#                 event=self.convention.name)
#         )
#         self.user.is_staff = True
#         self.user.save()
#         organisers.user_set.add(self.user)

    @classmethod
    def create(cls, ticket):
        first_name = ticket.first_name.title()
        last_name = ticket.last_name.title()
        email = ticket.email.lower()
        new_password = None

        participant, is_new = cls.objects.get_or_create(
            email=email,
        )

        if is_new:
            username = participant.email.split('@')[0]
            while Participant.objects.filter(username=username):
                username = username + "2"
            new_password = User.objects.make_random_password()
            participant.first_name = first_name
            participant.last_name = last_name
            participant.username = username
            participant.set_password(new_password)
            participant.save()

        return participant

    @classmethod
    def activate_all_tickets(cls):
        for ticket in Ticket.objects.all():
            cls.create(ticket)

    def assigned_games(self):
        return self.signup_set.exclude(
            status__in=[
                Signup.NOT_ASSIGNED,
                Signup.WAITING_LIST]).filter(
            session__programitem__item_type__stars=4).order_by('session__start_time')

    def check_missing_signup(self):
        """ Mark participant as not signed up """
        no_signups = ProgramSession.objects.filter(programitem__item_type__name__icontains='no signup')
        for session in no_signups:
            # session.signup_set.all().delete()
            signups = Signup.objects.filter(
                participant=self, session=session.same_time_sessions(),
            ).exclude(
                status=Signup.NOT_ASSIGNED, priority=0,
            ).count()
            if signups == 0:
                signup = Signup(
                    participant=self,
                    session=session,
                    status=Signup.VOLUNTEER,
                )
                signup.save()


class ItemType(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(blank=True, max_length=1000)
    stars = models.PositiveSmallIntegerField(
        help_text=_('Max stars that participants can give during signup.'),
        default=4,
    )
    color = models.CharField(
        max_length=7, default="#FFF", help_text="html colour")
    ordering = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def css_class(self):
        return "program_" + self.name.lower().replace(" ", "")

    class Meta:
        ordering = ["ordering", "name", ]


class LocationManager(models.Manager):

    def public(self):
        return super().exclude(staff_only=True)

    def private(self):
        return super().all()


class Location(models.Model):
    objects = LocationManager()
    name = models.CharField(max_length=50)
    description = models.CharField(blank=True, max_length=5000)
    max_capacity = models.IntegerField(
        blank=True, null=True,
    )
    staff_only = models.BooleanField(default=False)
    ordering = models.IntegerField(default=0)
    convention = models.ForeignKey(
        Convention,
        related_name='event',
        default=next_convention,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["ordering", "name", ]


class ProgramItem(models.Model):
    DEFAULT_LENGTH = 60 * 4
    PROGRAM_TYPES = (
        ('Larp', 'Larp'),
        ('Freeform', 'Freeform game'),
        ('Workshop', 'Workshop'),
        ('Lecture', 'Lecture'),
        ('Social', 'Social event'),
        ('Other', 'Other'),
    )
    LANGUAGES = (
        ('EN', 'English'),
        ('NO', 'Scandinavian'),
    )
    convention = models.ForeignKey(
        Convention,
        default=next_convention,
    )
    name = models.CharField(
        max_length=100,
        help_text='The name of this programme item',
    )
    description = models.TextField(
        help_text='Description of the event',
    )
    item_type = models.ForeignKey(ItemType)

    language = models.CharField(
        max_length=2,
        choices=LANGUAGES,
        default=LANGUAGES[0][0],
    )
    start_time = models.DateTimeField(
        default=next_convention_start_time
    )
    duration = models.PositiveSmallIntegerField(
        default=DEFAULT_LENGTH,
        help_text='Length in minutes',
    )
    location = models.ManyToManyField(
        Location,
        blank=True,
    )

    organisers = models.ManyToManyField(
        Participant,
        related_name='organised_by',
        blank=True,
    )

    max_participants = models.IntegerField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

    def assign_organisers_as_game_masters(self):
        for o in self.organisers.all():
            for s in self.programsession_set.all():
                signup, new = Signup.objects.get_or_create(
                    participant=o,
                    session=s,
                )
                signup.status = Signup.GAME_MASTER
                signup.save()


class ProgramSession(models.Model):
    programitem = models.ForeignKey(
        ProgramItem,
    )
    location = models.ForeignKey(
        Location,
    )
    start_time = models.DateTimeField(
        default=next_convention_start_time
    )
    end_time = models.DateTimeField(
        blank=True,
        null=True,
    )
    participants = models.ManyToManyField(
        Participant,
        blank=True,
        through='Signup',
    )
    popularity = models.FloatField(
        default=0.0,
    )

    def calculate_popularity(self):
        # signups = self.signup_set.order_by('-priority')[0:self.max_participants]
        # if signups:
        #     return statistics.mean(signups.values_list('priority', flat=True))
        signups = self.signup_set.filter(priority__gt=self.programitem.item_type.stars / 2).count()
        if self.max_participants:
            return signups / self.max_participants
        elif self.signup_set.count():
            return signups / self.signup_set.count()
        else:
            return 0

    def same_time_sessions(self):
        sessions = ProgramSession.objects.exclude(
            start_time__gte=self.end_time).exclude(
            end_time__lte=self.start_time)
        return sessions

    def players(self):
        players = self.signup_set.exclude(status__in=(
            Signup.NOT_ASSIGNED, Signup.WAITING_LIST)
        ).order_by(
            'ordering').prefetch_related('participant')
        return players

    @property
    def max_participants(self):
        return self.programitem.max_participants

    @property
    def duration(self):
        return self.programitem.duration

    def save(self):
        self.end_time = self.start_time + timedelta(
            minutes=self.programitem.duration,
        )
        self.popularity = self.calculate_popularity()
        return super().save()

    def __str__(self):
        return '{item}, {time}'.format(
            item=self.programitem.name,
            time=self.start_time.strftime("%a %H:%M"),
        )

    def game_masters(self):
        gamemasters = self.signup_set.filter(status=Signup.GAME_MASTER)
        return gamemasters
        # return [gm.participant.get_full_name() for gm in gamemasters]

    def game_masters_count(self):
        return self.game_masters().count()

    def assigned_participants(self):
        return self.signup_set.exclude(status=Signup.NOT_ASSIGNED).order_by('-status', '-priority')

    def participants_signed_up(self):
        return self.signup_set.exclude(priority=0).count()


class Signup(models.Model):
    GAME_MASTER = 1
    PARTICIPANT = 2
    PREASSIGNED = 3
    VOLUNTEER = 4
    WAITING_LIST = 5
    NOT_ASSIGNED = 0

    STATUS_CHOICES = (
        (GAME_MASTER, _('Game Master'),),
        (PREASSIGNED, _('Preassigned'),),
        (VOLUNTEER, _('Volunteer'),),
        (PARTICIPANT, _('Participant'),),
        (NOT_ASSIGNED, _('Not assigned'),),
        (WAITING_LIST, _('Waiting list'),),
    )

    class Meta:
        unique_together = (
            ("session", "participant",),
        )
        ordering = [
            "-status",
            "-ordering",
            "-priority",
        ]

    def validate_unique(self, *args, **kwargs):
        old = Signup.objects.filter(session=self.session, participant=self.participant)
        if old.count() == 1:
            old_signup = old[0]
            if old_signup.pk != self.pk:
                self.pk = old_signup.pk
                old_signup.delete()

        super().validate_unique(*args, **kwargs)

    session = models.ForeignKey(ProgramSession)
    participant = models.ForeignKey(Participant)
    updated = models.DateTimeField(auto_now=True)
    priority = models.IntegerField(
        default=0,
        help_text="chosen by the user",
    )
    status = models.IntegerField(
        default=NOT_ASSIGNED,
        choices=STATUS_CHOICES,

applications/program/templates/_program_info.html
<h2>Sign up for the Program</h2>
<p>Please choose which larps you want to attend by giving them 1-4 hearts. Giving a larp zero hearts means you would prefer to have a break and not play in this section over playing that larp.</p>
<p>Spots are not allocated on a first come, first served basis. Instead, the number of hearts will be used to generate a list of how you prioritize the larps relatively to each other. The system will allocate the spots based on the priorities in order to give everyone something they want to play.</p>
<p>You can sign up for as many larps as you want. Thursday, we will distribute the spots in all the games. You will receive an email with with games you have been assigned to.</p>
<p>We will make sure no-one is assigned to play more than one game at a time, and that you will not be assigned to two sessions of the same game.</p>
<p>You can change the distribution of your hearts until the deadline, {{ convention.program_signup_closes }}.</p>
<p class='strong'>Regardless of larp venue, meet up for all larps at Slurpen 30 mins before start</p>

<h2>Game masters and game hosts</h2>
<p>If you are assigned as a game master or game host in a game, you will not be assigned as a player in any game that happens at that time. Feel free to put priorities in those games anyway, in case there are any program changes.</p>

<h2>Meals</h2>
<p>There will be meals served at Slurpen for the price of NOK 50. Please sign up for the meals you want to take part in. The food will be vegan, lactose-free, gluten-free. There are also several restaurants and fast food joints nearby Grenselandet if you want to eat something else</p>

applications/program/templates/_program_menu.html
<a href="{% url 'program-sessionlist' %}">List of games</a> | <a href="{% url 'program-participants' %}">List of players</a>

applications/program/templates/blekke.html
<html>
    <head>
    </head>
    <body>
        <h2> Program </h2>
        {% for p in programitems %}
        <p><strong>{{ p.itemtype }}:{{p.name}}</strong></p>
        <p>{% for user in p.organisers.all %} {{ user.get_full_name }}{% if not forloop.last %},{% endif %}{% endfor %}</p> 
        <p>{{p.start_time|date:"D, H:i"}}&mdash;{{p.end_time|date:"H:i"}},
        {{ p.location }}
        <p>
        {% if p.description %}{{ p.description }}
        {% else %}&nbsp;{% endif %}
        </p>
        {% endfor %}
        <h2> Schedule </h2>
        {% for p in schedule %}
        {% ifchanged %}<h3>{{p.start_time|date:"l"}}</h3>{% endifchanged %}
        {% ifchanged %}<h4>{{p.location}}</h4>{% endifchanged %}
        <p>{{ p.name }};;{{ p.itemtype }};;{{p.start_time|date:"H:i"}}&mdash;{{p.end_time|date:"H:i"}},
        {% endfor %}
    </body>
</html>

applications/program/templates/fordeling.html
<html>
<head></head>
<body>

{% for key, myItem in g_list.items %}
	<div>
	<h1>{{myItem.programitem.name}}</h1>
	<table>
	<tr><td>Starts at:</td><td>{{myItem.programitem.start_time}}</td></tr>
	<tr><td>Ends at:</td><td>{{myItem.programitem.end_time}}</td></tr>
	<tr><td>Organisers:</td><td>{% for organiser in myItem.programitem.organisers.all %} {{organiser}},{% endfor %}</td></tr>
	<tr><td>Description:</td><td>{{myItem.programitem.description}}</td></tr>
	<tr><td>Max Participants:</td><td>{{myItem.programitem.max_participants}}</td></tr>
	<tr><td>Will Show:</td><td>{{myItem.will_show}}</td></tr>
	</table>

	<table>
	<tr><td colspan = "3">{{myItem.programitem.name}}</td></tr>
	<tr><td>#</td><td>name</td><td>priority</td></tr>	
	{% for signup in myItem.signups %}
		<tr {% if forloop.counter0 < myItem.programitem.max_participants %} class = "ledig" {% endif %}>
		<td>{{ forloop.counter }}</td>
		<td>{% if forloop.counter > myItem.will_show %}({{ signup.participant }}){% else %}{{signup.participant}}{% endif %}</td>
		<td>{{ signup.priority }}</td>
		</tr>
	{% endfor %}
	</table>
{% endfor %}
	

{% endblock %}

{% block footer %}
	<b><a href = "/liste/">index</a></b> | 
	{% for item in programitems %}
	<a href = "/liste/{{item.id}}/">{{item.name}}</a> | 
	{% endfor %}
{% endblock %}

</body>
</html>

applications/program/templates/open_list.html
{% extends "program-template.html" %}

{% block title %}List of games and participants{% endblock %}

{% block content %}
<h1>List of games and participants</h1>
<p>Check in for all larps open 30 minutes before it starts and closes 20 minutes before it starts. If you are too late, the spot might be given to someone else.</p>
<p>If you're playing a blackbox larp, wear black, neutral clothes.</p>
<a href="/program/">View program schedule</a>
{% for mySession in sessions %}

	<table class="overview">
	<caption>{{mySession.programitem.name}} {{mySession.programitem.start_time}}</caption>
	<tr><th>Starts at:</td><td>{{mySession.start_time}}</td></tr>
	<tr><th>Ends at:</td><td>{{mySession.end_time}}</td></tr>
	<tr><th>Organisers:</td><td>{% for organiser in mySession.programitem.organisers.all %} {{organiser}},{% endfor %}</td></tr>
	<tr><th>Description:</td><td>{{mySession.programitem.description}}</td></tr>
	{% if mySession.max_participants > 0 %}<tr><th>Max Participants:</td><td>{{mySession.max_participants}}</td></tr> {% endif %}
	</table>

	<table class="overview">
	<tr><th>#</th><th>name</th></tr>
	{% for signup in mySession.assigned_participants %}
		<tr>
		<td>{% if signup.importance = 2 %}GM{% else %}{% endif %}</td>
		<td>{{ signup.participant }}</td>
		</tr>
	{% endfor %}
	</table>
{% endfor %}

{% endblock %}

{% block footer %}
{% endblock %}

applications/program/templates/oppslag.html
<html><head></head>
    <body>
        {% for p in sessions %}
        <p><strong>Tit:{{p.programitem.name}}</strong>
        </br>Max: {{p.max_participants}}
        </br>Time: {{p.start_time|date:"D H:i"}}&ndash;{{p.end_time|date:"D H:i"}}
        </br>Location: {{p.location}}
        {{ p.programitem.description|linebreaks }}
        </br>Participants:
            {% for n in p.players %}
            </br>{{ n.ordering }} {{ n.participant }}
            {% endfor %}
        </br>--
        {% endfor %}
        {% for participant in participants %}
            <strong>{{ participant.get_full_name }}</strong></br>
            {% for game in participant.assigned_games %}
                {% if game.status = game.GAME_MASTER %}GM{% endif %} {{ game.session }}</br>
            {% endfor game %}
            --</br>
        {% endfor %}
    </body>
</html>

applications/program/templates/participantlist.html
{% extends "program-admin.html" %}

{% block title %}Fordeling av spill{% endblock %}

{% block content %}
<table class="overview">
	<caption>List of participants and assigned games</caption>
	<tr>
		<th>Name</th>
		<th>#1</th>
		<th>#2</th>
		<th>#3</th>
	</tr>
	{% for participant in participants %}
	<tr>
		<td class="name">{{ participant.get_full_name }}</td>
		{% for game in participant.assigned_games %}
			<td>{% if game.status = game.GAME_MASTER %}GM{% endif %} {{ game.session }}</td>
		{% endfor game %}
	</tr>
	{% endfor %}
</table>
{% endblock content %}

applications/program/templates/program-admin.html
{% extends "base-template.html" %}
{% block header %}
 {% include "_program_menu.html" %}
{% endblock header %}
{% block footer %}
 {% include "_program_menu.html" %}
{% endblock footer %}

applications/program/templates/program-template.html
{% extends "base-template.html" %}

applications/program/templates/reshuffle.html
{% extends "program-admin.html" %}

{% block title %}Fordeling av spill{% endblock %}

{% block content %}

<h1>Reshuffle complete</h1>

{% endblock %}

applications/program/templates/schedule.html
{% extends "program-template.html" %}
{% load dajaxice_templatetags %}
{% load staticfiles %}
{% load sekizai_tags %}

{% block title %}Program Schedule{% endblock title %}

{% block content %}
{% addtoblock 'extrajs' %}
{% dajaxice_js_import %}
<script src="{{ STATIC_URL }}js/ratings.js"></script>
<script type="text/javascript">
    {% if registration_closed %}
    var registration_closed = true;
    {% else %}
    var registration_closed = false;
    {% endif %}
</script>
{% endaddtoblock %}
{% if participant %}
    <h1>Program preferences for {{ participant }}</h1>
    {% if not registration_closed %}
    <p>Please tell us what you would most like to play at Grenselandet 2014. This page might not work equally well in all web browsers. If you are having trouble, please try using Chrome.</p>
    <p>The signup closes at {{ convention.program_signup_closes }}</p>
    {% else %}
    <p>Signup for the program is closed.</p>
    {% endif %}

{% else %}
    <h1>Program Schedule</h1>
    <p>If you have a ticket for Grenselandet, we have sent instructions on how to sign up for programitems.</p>
{% endif %}
{% for day in schedule %}
<table class="schedule">
    <caption>
        {{ day.day| date:"l F dS"}}
    </caption>
    <tr>
        <td class="time">
            time / place
        </td>
        {% for room in day.rooms %}
        <td class="location">
            {{room.name}}
        </td>
        {% endfor room %}
    </tr>
    {% for hour in day.timetable %}
    <tr style="height: {{ PIXELS_PER_BLOCK }}px;">
        {% for cell in hour %}
        {% if forloop.first %}
        <td class="time" >
            {{cell.0| date:"H:i"}}
        </td>
        {% else %}
        <td class="timeslot">
            {% if cell %}
            <div class = "wrapper_fix">
            <div data-tooltip aria-haspopup="true" class="has-tip program_item {{ cell.session.programitem.item_type.css_class }}" style="height: {{ cell.height }}px;"
            title="
            <h3>{{ cell.session.programitem.name }}</h3>
            {% if cell.gamemasters %}
              <p>Gamemasters:{% for gm in cell.gamemasters %} {{ gm.participant.get_full_name }}, {% endfor %}</p>
            {% endif %}
            {{ cell.session.programitem.description|linebreaks }}"
            >

                <div class="rating">
                    {% if cell.signup.status = GAME_MASTER %}
                        <span class="data">99</span>
                        <div class="starcontainer">
                            <div class="jquery-ratings-organiser"
                            title="You are a game master"><strong> GM</strong></div>
                        </div>

                    {% else %}
                        <span class="data">
                            {{ cell.signup.priority }}
                            {{ cell.signup.pk }}
                            {{ cell.stars }}
                        </span>
                        <div class="starcontainer"></div>
                    {% endif %}
                </div>
                <div class="description">
                    <noscript>You must enable javascript to sign up to </noscript>
                    {{cell.session.programitem.name}}</div>

                {% if perms.program.change_programitem %}
                    {% with cell.session.players as players %}
                        <div data-tooltip aria-haspopup="true" class="has-tip players" title="
                        <h3>Players: {{ players.count }} of {{ cell.session.max_participants }}</h3>
                        <p>
                        {% for player in players %}
                        {{ player.ordering }} {{ player.participant }} {{ player.priority }}</br>
                        {% endfor %}</p>">
                            {{ players.count }}
                        </div>
                    {% endwith %}
                    <div class="edit_program" title="edit item">
                        <a href="{% url "admin:program_programitem_change" cell.session.programitem.id %}">&#xf194;</a>
                    </div>
                {% endif %}

            </div>
            </div>
            {% endif %}
        </td>
        {% endif %}
        {% endfor cell %}
    </tr>
    {% endfor hour %}
</table>
<hr>
{% endfor day %}
{% if participant %}
{% include '_program_info.html' %}
{% endif %}
{% endblock content %}

applications/program/templates/sessionlist.html
{% extends "program-admin.html" %}

{% block title %}Fordeling av deltagere{% endblock %}

{% block content %}
	{% for mySession in sessions %}
		<table class="overview">
		<caption>{{mySession.programitem.name}} {{mySession.programitem.start_time}}</caption>
		<tr><th>Location:</th><td>{{mySession.location.name}}</td></tr>
		<tr><th>Starts at:</th><td>{{mySession.start_time}}</td></tr>
		<tr><th>Ends at:</th><td>{{mySession.end_time}}</td></tr>
		<tr><th>Organisers:</th><td>{% for organiser in mySession.programitem.organisers.all %} {{organiser}},{% endfor %}</td></tr>
		<tr><th>Description:</th><td>{{mySession.programitem.description}}</td></tr>
		{% if mySession.max_participants > 0 %}<tr><th>Max Participants:</th><td>{{mySession.max_participants}}</td></tr> {% endif %}
		</table>

		<table class="overview">
		<tr><th>#</th><th>name</th><th>choice#</th></tr>
		{% for signup in mySession.assigned_participants %}
			<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ signup.participant }}</td>
			<td>{% if signup.importance = 2 %}GM{% else %}{{ signup.choice_number}}{% endif %}</td>
			</tr>
		{% endfor %}
		</table>
	{% endfor %}
{% endblock content %}